name: "Cura-plugin release"

on:
  push:
    tags:
      - "v*"

jobs:
  create-curapackages:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          path: "repo"
          submodules: "recursive"
      - name: Create folder for files which are part of plugin
        run: mkdir -p build
      - name: Copy files needed for the build
        working-directory: repo
        run: |
          cp -r categories ../build/
          cp -r licenses ../build/
          cp -r models ../build/
          cp -r qml ../build/
          cp -r resources/i18n ../build/resources/
          cp __init__.py ../build/
          cp attributions ../build/
          cp LICENSE ../build/
          cp plugin.json ../build/
          cp README.md ../build/
          cp ShapesData.py ../build/
          cp StacksOfShapes.py ../build/
          cp SymbolsData.py ../build/
      - uses: fieldOfView/cura-plugin-packager-action@main
        with:
          source_folder: "build"
          package_info_path: "build/.github/workflows/package.json"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.curapackage
